### ISSUE TITLE
Add support for multiple games in the same post

### ISSUE THREAD

**Issue by sahilthapar** [sahilthapar/meeple-matchmaker#8]

**Comment by thobicex** [comment]
I did successful survey for this year already, I need some information to verify my identity.

> This storm will get to an end once I get my address fixed.

**Comment by thobicex** [comment]
Where can you make use of Nift gift card to match with new games?

**Comment by thobicex** [comment]
Can suggestions new business place's to proclaimed the certificate ecode nift gift card sales for games, of which you can exchange Nift gift cards online purchases to paid object utilities?
